[package]
authors = ["Lucas Pickering <lucas@lucaspickering.me>"]
description = "Easily switch between common values for arbitrary environment variables"
edition = "2021"
keywords = ["env", "environment", "export"]
license = "MIT"
name = "env-select"
repository = "https://github.com/LucasPickering/env-select"
version = "0.1.1"

[[bin]]
name = "es"
path = "src/main.rs"

[dependencies]
anyhow = {version = "1.0.65", features = ["backtrace"]}
atty = "0.2.14"
clap = {version = "4.0.17", features = ["derive"]}
dialoguer = {version = "0.10.2", default-features = false}
env_logger = {version = "0.9.1", default-features = false, features = ["atty", "termcolor"]}
log = "0.4.17"
serde = {version = "1.0.145", default-features = false, features = ["derive"]}
toml = {version = "0.5.9", default-features = false}
